name: Main Branch Deploy

on:
  push:
    branches:
      - main

jobs:

  docker_push:
    name: "Push docker image"
    uses: "philipcristiano/workflows/.github/workflows/docker-build-push.yml@main"
    needs: [flake, rust]
    with:
      repository: ${{ github.repository }}
      timeout: 25

    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  rust:
    uses: "philipcristiano/workflows/.github/workflows/rust.yml@main"

  flake:
    uses: "philipcristiano/workflows/.github/workflows/nix.yml@main"
    with:
      flakes-from-devshell: true
      script: |
        cargo build
        cargo run --
